### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by bahador-r** [alternadom/WiFiFlutter#117]
when i call `WiFiForIoTPlugin.setWiFiAPSSID(psSSID)`, i get this error:

`E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:601)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Binder.execTransact(Binder.java:731)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555):
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555):
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:131)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.getWiFiAPPreSharedKey(WifiIotPlugin.java:341)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:248)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Looper.loop(Looper.java:160)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10057)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.createException(Parcel.java:1950)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.readException(Parcel.java:1918)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.readException(Parcel.java:1868)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1731)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2152)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	... 14 more
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555):
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:131)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.setWiFiAPSSID(WifiIotPlugin.java:297)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:239)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Looper.loop(Looper.java:160)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10057)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.createException(Parcel.java:1950)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.readException(Parcel.java:1918)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.os.Parcel.readException(Parcel.java:1868)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1731)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2152)
E/class info.whitebyte.hotspotmanager.WifiApManager( 3555): 	... 14 more
E/MethodChannel#wifi_iot( 3555): Failed to handle method call
E/MethodChannel#wifi_iot( 3555): java.lang.NullPointerException: Attempt to write to field 'java.lang.String android.net.wifi.WifiConfiguration.SSID' on a null object reference
E/MethodChannel#wifi_iot( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.setWiFiAPSSID(WifiIotPlugin.java:299)
E/MethodChannel#wifi_iot( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:239)
E/MethodChannel#wifi_iot( 3555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#wifi_iot( 3555): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#wifi_iot( 3555): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#wifi_iot( 3555): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#wifi_iot( 3555): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#wifi_iot( 3555): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#wifi_iot( 3555): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#wifi_iot( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#wifi_iot( 3555): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#wifi_iot( 3555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
E/flutter ( 3555): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Attempt to write to field 'java.lang.String android.net.wifi.WifiConfiguration.SSID' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'java.lang.String android.net.wifi.WifiConfiguration.SSID' on a null object reference
E/flutter ( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.setWiFiAPSSID(WifiIotPlugin.java:299)
E/flutter ( 3555): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:239)
E/flutter ( 3555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 3555): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 3555): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 3555): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3555): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 3555): 	at android.os.Looper.loop(Looper.java:160)
E/flutter ( 3555): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 3555): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3555): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 3555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
E/flutter ( 3555): )
E/flutter ( 3555): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter ( 3555): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555): #2      WiFiForIoTPlugin.setWiFiAPSSID
package:wifi_iot/wifi_iot.dart:122
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555): #3      _InternetPageState.storeAndConnectWiFi
package:machine/…/setup/internetPage.dart:66
E/flutter ( 3555): <asynchronous suspension>
E/flutter ( 3555):
`

**Comment by daadu** [comment]
@bahador-r WifiAP mode feature is out of date, it is being worked on #114.

@bahador-r Your contributions are welcomed.
