### ISSUE TITLE
Wi-Fi disable is not working

### ISSUE THREAD

**Issue by JAICHANGPARK** [alternadom/WiFiFlutter#82]
I'd like to disable wi-fi when it activated

```
  await WiFiForIoTPlugin.setEnabled(false);
  WiFiForIoTPlugin.forceWifiUsage(false);
```
this code is not works for me 
how to disable wi-fi ?

**Comment by JAICHANGPARK** [comment]
```
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:128)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.isSSIDHidden(WifiIotPlugin.java:235)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:168)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Looper.loop(Looper.java:142)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.app.ActivityThread.main(ActivityThread.java:6528)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10265)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:2013)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:1959)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1793)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2255)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	... 14 more
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:128)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.isSSIDHidden(WifiIotPlugin.java:235)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:168)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Looper.loop(Looper.java:142)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.app.ActivityThread.main(ActivityThread.java:6528)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10265)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:2013)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:1959)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1793)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2255)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	... 14 more
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:128)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.getWiFiAPSSID(WifiIotPlugin.java:210)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:162)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Looper.loop(Looper.java:142)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.app.ActivityThread.main(ActivityThread.java:6528)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10265)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:2013)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:1959)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1793)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2255)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	... 14 more
E/flutter (23945): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'Future<Null>?'
E/flutter (23945): #0      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
E/flutter (23945): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
E/flutter (23945): #2      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
E/flutter (23945): #3      Future._completeError (dart:async/future_impl.dart:537:5)
E/flutter (23945): #4      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
E/flutter (23945): #5      WiFiForIoTPlugin.isWiFiAPSSIDHidden (package:wifi_iot/wifi_iot.dart)
E/flutter (23945): <asynchronous suspension>
E/flutter (23945): #6      _FlutterWifiIoTState.initState (package:wifi_iot_example/main.dart:53:22)
E/flutter (23945): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (23945): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (23945): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (23945): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (23945): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
E/flutter (23945): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
E/flutter (23945): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
E/flutter (23945): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
E/flutter (23945): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
E/flutter (23945): #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
E/flutter (23945): #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
E/flutter (23945): #18     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (23945): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (23945): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (23945): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (23945): #22     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (23945): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (23945): #24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (23945): #25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (23945): #26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (23945): #27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (23945): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23945): 
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): java.lang.reflect.InvocationTargetException
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at info.whitebyte.hotspotmanager.WifiApManager.getWifiApConfiguration(WifiApManager.java:128)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.getWiFiAPPreSharedKey(WifiIotPlugin.java:265)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:174)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Looper.loop(Looper.java:142)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.app.ActivityThread.main(ActivityThread.java:6528)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi Ap config (uid = 10265)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:2013)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.os.Parcel.readException(Parcel.java:1959)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.IWifiManager$Stub$Proxy.getWifiApConfiguration(IWifiManager.java:1793)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	at android.net.wifi.WifiManager.getWifiApConfiguration(WifiManager.java:2255)
E/class info.whitebyte.hotspotmanager.WifiApManager(23945): 	... 14 more
I/zygote64(23945): Background concurrent copying GC freed 35704(1448KB) AllocSpace objects, 0(0B) LOS objects, 59% free, 1061KB/2MB, paused 5.781ms total 13.608ms

```


## Flutter Env

- [✓] Flutter (Channel beta, 1.22.0, on Microsoft Windows

**Comment by JAICHANGPARK** [comment]
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
```

**Comment by JAICHANGPARK** [comment]
- now setWifiEnabled is always return false
- sdk 28

**Comment by guyluz11** [comment]
I have the same errors.

**Comment by daadu** [comment]
@JAICHANGPARK `setEnabled` turns on/off wifi module, while `setWiFiAPEnabled` turn on/off AP ("hotspot") module.

`setWifiAPEnabled` implmenetation is out of date and is being worked on #114.

`setEnabled` will always return `false` since the Android API is deprecated after v29.

The information provided is mentioning both, can you clarify what are you looking for?

**Comment by daadu** [comment]
This feature/fix has landed on pub.dev with [v0.3.1](https://pub.dev/packages/wifi_iot/versions/0.3.1).
